[CSL-2597] Add to favorites button
Constructor-io/constructorio-ui-quizzes pull request #107
Opened 2023-07-28 05:36 UTC by stanlp1

2023-07-28 21:22 UTC, esezen reviewed
This is looking great. Can you add `onAddToFavoritesClick` to `functionStrings` in `utils`?
![image](https://github.com/Constructor-io/constructorio-ui-quizzes/assets/2954126/0e3d3f57-f9cd-460a-b130-7ebc98c6a8cc)

Also do you mind reaching out to Mariano to see if he is happy with the size of the icon? We don't need to wait for his response, we can merge this and change the size in a different PR if needed

2023-07-29 23:37 UTC, mocca102 requested changes
Can we add another SVG with a filled heart when add_to_favorites fire and only fire the event if the favorites icon isn't active/clicked already. Basically like a toggle since currently the icon doesn't change on click and it looks as if it's not working

2023-07-29 23:37 UTC, mocca102 commented on src/components/CioQuiz/index.tsx
> +    customAddToFavoritesCallback: !!resultsPageOptions?.onAddToFavoritesClick,
Why add `customAddToFavoritesCallback` to the customer facing interface? I'm not opposed to using it just why return it in the hook? I think we can remove it along with `customClickItemCallback`

2023-08-01 21:06 UTC, mocca102 commented on src/components/CioQuiz/index.tsx
> +    customAddToFavoritesCallback: !!resultsPageOptions?.onAddToFavoritesClick,
Ignore this please

2023-08-02 14:32 UTC, mocca102 commented on src/components/ResultFavoritesButton/ResultFavoritesButton.tsx
> +  const clickHandler = () => {
Lets not have any logic in presentational components and have the logic in hooks

2023-08-02 14:32 UTC, mocca102 commented on src/components/ResultFavoritesButton/ResultFavoritesButton.tsx
> +  const [isFavorited, setIsFavorited] = useState(false);
Lets not have any logic in presentational components and have the logic in hooks

2023-08-03 13:23 UTC, mocca102 commented
Thanks for making the changes, looking way better. Just a couple of things
- Misspelling in file name useAddToFavoritesbuttonProps -> useAddToFavoritesButtonProps
- Conversion event should only fire if favorites button isn't already clicked
- Not sure if it's this PR but single result card is misaligned 
![Uploading Screenshot 2023-08-03 at 4.22.54 PM.png…]()

2023-08-03 13:24 UTC, mocca102 requested changes
Thanks for making the changes, looking way better. Just a couple of things

- Misspelling in file name useAddToFavoritesbuttonProps -> useAddToFavoritesButtonProps
- Conversion event should only fire if favorites button isn't already clicked
- Not sure if it's this PR but single result card is misaligned
<img width="1428" alt="Screenshot 2023-08-03 at 4 22 54 PM" src="https://github.com/Constructor-io/constructorio-ui-quizzes/assets/58053149/fa686c58-ce9c-4b05-81ab-f0288f1ac033">

2023-08-03 14:39 UTC, mocca102 commented
Ignore the visual bug. Enes fixed it in another PR @stanlp1

2023-08-04 15:55 UTC, mocca102 approved these changes
LGTM!

2023-08-07 13:08 UTC, merged