[csl-2833] scroll to top between questions
Constructor-io/constructorio-ui-quizzes pull request #133
Opened 2023-09-25 18:15 UTC by HHHindawy

2023-09-27 17:01 UTC, mocca102 commented
You'll need a way to access the ref though since the title is nested and you can access it directly from CioQuiz -> index.tsx

2023-09-27 17:03 UTC, mocca102 commented
Or maybe you can create the ref on index.tsx and then forward it to the question title. I'm not sure if this is the best solution though

2023-09-27 17:08 UTC, mocca102 requested changes

2023-09-28 17:18 UTC, stanlp1 commented on src/components/CioQuiz/index.tsx
> +    // Scroll to the top of quiz
Agreed, also in case someone ever has multiple quizzes on the same page.

Should we also make this a toggled feature?

2023-10-04 13:19 UTC, HHHindawy commented
Closing this PR since customers will be the ones handling this if they want to.

2023-10-04 13:19 UTC, closed without merging