[CSL-2278] Add question specific classes
Constructor-io/constructorio-ui-quizzes pull request #55
Opened 2023-04-24 21:05 UTC by stanlp1

2023-04-24 21:06 UTC, stanlp1 commented on src/styles.css
> +  display: flex;
Not having display flex breaks our current styles.

2023-04-24 21:06 UTC, stanlp1 commented on src/components/QuizQuestions/index.tsx
> +    <div className={nextQuestion?.id ? `cio-question-id-${nextQuestion?.id}` : ''}>
I added another div here, should we keep it here or move it into the respective question types?

2023-04-24 23:21 UTC, stanlp1 commented on src/components/QuizQuestions/index.tsx
> +    <div className={nextQuestion?.id ? `cio-question-id-${nextQuestion?.id}` : ''}>
Moved it in each individual just to be safe, not somehow affect styles with this added div.

2023-06-13 16:48 UTC, esezen requested changes
This is looking great. It looks like Quizzes team added the key to individual options of select question as well. Can we add that too?
I don't love the naming of the attribute (`key`). I pinged Quizzes team about that

----------------------

Separately, I know the story says class but did we consider making this a data attribute? Are there any pros/cons for class vs data attribute?

2023-06-16 17:23 UTC, stanlp1 commented
> This is looking great. It looks like Quizzes team added the key to individual options of select question as well. Can we add that too? ~I don't love the naming of the attribute (`key`). I pinged Quizzes team about that~
> 
> Separately, I know the story says class but did we consider making this a data attribute? Are there any pros/cons for class vs data attribute?

Data attribute makes sense. I think there might be slight benefits for selector speed when using classes but I don't think that matters much. Will update.

2023-06-16 18:24 UTC, esezen approved these changes
LGTM!

2023-06-20 13:06 UTC, merged